language: php
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --prefer-source
script: phpunit --bootstrap vendor/autoload.php tests/
php:
  - 5.3
  - 5.4
