<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phutil', 'parser/aast/api/token');


phutil_require_source('XHPASTToken.php');
